image: Visual Studio 2017
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
before_build:
- cmd: nuget restore Snowplow.Analytics.Extractor.sln -SolutionDirectory .
build:
  verbosity: minimal
test_script:
- cmd: vstest.console /logger:Appveyor Snowplow.Analytics.Extractor.Tests\bin\Debug\Snowplow.Analytics.Extractor.Tests.dll
